baseURL = "http://docs.joinmastodon.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Mastodon documentation"
pygmentsCodeFences = true
pygmentsStyle = "dracula"
metaDataFormat = "yaml"
paginate = 100
enableGitInfo = true

[languages.en.menu]
  [[languages.en.menu.docs]]
    name = "Using Mastodon"
    weight = 10
    identifier = "user"
    url = "/user/"
  [[languages.en.menu.docs]]
    name = "Running Mastodon"
    weight = 20
    identifier = "admin"
    url = "/admin/"
  [[languages.en.menu.docs]]
    name = "Developing Mastodon apps"
    weight = 30
    identifier = "client"
    url = "/client/"
  [[languages.en.menu.docs]]
    name = "Contributing to Mastodon"
    weight = 40
    identifier = "dev"
    url = "/dev/"
  [[languages.en.menu.docs]]
    name = "Spec compliance"
    weight = 50
    identifier = "spec"
    url = "/spec/"
  [[languages.en.menu.docs]]
    name = "REST API"
    weight = 60
    identifier = "api"
    url = "/api/"
  [[languages.en.menu.docs]]
    name = "API Methods"
    weight = 70
    identifier = "methods"
    url = "/methods/"
  [[languages.en.menu.docs]]
    name = "API Entities"
    weight = 80
    identifier = "entities"
    url = "/entities/"


[languages.zh-cn.menu]
  [[languages.zh-cn.menu.docs]]
    name = "使用长毛象"
    weight = 10
    identifier = "user"
    url = "/user/"
  [[languages.zh-cn.menu.docs]]
    name = "运营长毛象"
    weight = 20
    identifier = "admin"
    url = "/admin/"
  [[languages.zh-cn.menu.docs]]
    name = "开发长毛象应用"
    weight = 30
    identifier = "client"
    url = "/client/"
  [[languages.zh-cn.menu.docs]]
    name = "向长毛象项目做贡献"
    weight = 40
    identifier = "dev"
    url = "/dev/"
  [[languages.zh-cn.menu.docs]]
    name = "Spec compliance"
    weight = 50
    identifier = "spec"
    url = "/spec/"
  [[languages.zh-cn.menu.docs]]
    name = "REST API"
    weight = 60
    identifier = "api"
    url = "/api/"
  [[languages.zh-cn.menu.docs]]
    name = "API Methods"
    weight = 70
    identifier = "methods"
    url = "/methods/"
  [[languages.zh-cn.menu.docs]]
    name = "API Entities"
    weight = 80
    identifier = "entities"
    url = "/entities/"


[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = -99

  [languages.zh-cn]
    contentDir = "content/zh-cn"
    languageName = "简体中文"
    weight = 1